name = "FeatureRelevance"
uuid = "040f642a-ad44-44b2-91d4-df3a5c5fa484"
version = "0.3.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InformationMeasures = "96684042-fbdc-5399-9b8e-d34e539a126c"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
AxisKeys = "0.1"
DataFrames = "1"
InformationMeasures = "0.3"
LightGBM = "0.5"
MLUtils = "0.2"
Missings = "1"
RecipesBase = "1"
Requires = "1"
StatsBase = "0.33"
Tables = "1"
julia = "1.6"

[extras]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AxisKeys", "DataFrames", "LightGBM", "Plots", "Test"]
